name: breakpoints
description: A new Flutter package.
version: 0.0.1
homepage: https://github.com/koji-1009/breakpoints

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
